import { ServiceRecord } from '../types';

export const MOCK_DATA: ServiceRecord[] = [
  {
    id: "4631",
    caseId: "869484",
    orderDescription: "Caso 00869484 - DESINSTALACION - 00146373 - TIGO - 700 MHZ - SAT7011 - CIAGA_TRAS",
    serviceType: "ENVIO",
    department: "SANTANDER",
    municipality: "MATANZA",
    difficulty: "BAJO",
    beneficiary: "JHONNY MARTINEZ",
    date: "30/12/2025",
    acta: "ACT-2025-001",
    valueLabor: 1005600,
    valueAdditionalDay: 0,
    valueFailedVisit: 0,
    valueCivilWorks: 0,
    valueTransport: 0,
    advanceAmount: 147600,
    totalAdvances: 147600,
    iva: 191064,
    reteFuente: 35000,
    reteIca: 9600,
    otherDiscounts: 0,
    subtotalService: 1005600,
    totalService: 1005600,
    balanceLabor: 1152064,
    balanceToPay: 1004464,
    status: 'Pendiente',
    observation: "Pendiente revisión de soportes físicos."
  },
  {
    id: "4632",
    caseId: "874748",
    orderDescription: "Caso 00874748 - INSTALACION - 00153485 - CLARO ODH - BOL - PUEBLO NUEVO REGENCIA",
    serviceType: "INSTALACION",
    department: "BOLIVAR",
    municipality: "MONTECRISTO",
    difficulty: "ALTO",
    beneficiary: "JHONNY MARTINEZ",
    date: "30/12/2025",
    acta: "",
    valueLabor: 0,
    valueAdditionalDay: 0,
    valueFailedVisit: 0,
    valueCivilWorks: 0,
    valueTransport: 0,
    advanceAmount: 169400,
    totalAdvances: 0,
    iva: 0,
    reteFuente: 0,
    reteIca: 0,
    otherDiscounts: 0,
    subtotalService: 0,
    totalService: 0,
    balanceLabor: 0,
    balanceToPay: 0,
    status: 'Abierto',
    observation: ""
  },
  {
    id: "4633",
    caseId: "852249",
    orderDescription: "CASO 852249 - INSTALACION - 00151398 - CLARO ODH - MET - PUERTO SIARE",
    serviceType: "INSTALACION",
    department: "META",
    municipality: "MAPIRIPAN",
    difficulty: "ALTO",
    beneficiary: "JHONNY MARTINEZ",
    date: "30/12/2025",
    acta: "",
    valueLabor: 0,
    valueAdditionalDay: 0,
    valueFailedVisit: 0,
    valueCivilWorks: 0,
    valueTransport: 0,
    advanceAmount: 42200,
    totalAdvances: 0,
    iva: 0,
    reteFuente: 0,
    reteIca: 0,
    otherDiscounts: 0,
    subtotalService: 0,
    totalService: 0,
    balanceLabor: 0,
    balanceToPay: 0,
    status: 'Abierto',
    observation: ""
  },
  {
    id: "4639",
    caseId: "874515",
    orderDescription: "CASO 874515 - MIGRACION - TIGO - 700 MHZ - GUV7010 - PUERTO NUEVO",
    serviceType: "MIGRACION",
    department: "GUAVIARE",
    municipality: "SAN JOSE DEL GUAVAIRE",
    difficulty: "MEDIO",
    beneficiary: "JHONNY MARTINEZ",
    date: "30/12/2025",
    acta: "",
    valueLabor: 0,
    valueAdditionalDay: 0,
    valueFailedVisit: 0,
    valueCivilWorks: 0,
    valueTransport: 0,
    advanceAmount: 307200,
    totalAdvances: 0,
    iva: 0,
    reteFuente: 0,
    reteIca: 0,
    otherDiscounts: 0,
    subtotalService: 0,
    totalService: 0,
    balanceLabor: 0,
    balanceToPay: 0,
    status: 'Abierto',
    observation: ""
  },
  {
    id: "4640",
    caseId: "886997",
    orderDescription: "Caso 00886997 - INSTALACION - UNE - REDITOS EMPRESARIALES - LEO - SAN ROQUE ANTIOQUIA - PUERTO NUS",
    serviceType: "LEGALIZACION",
    department: "ANTIOQUIA",
    municipality: "SAN ROQUE",
    difficulty: "MEDIO",
    beneficiary: "FERNANDO CAICEDO",
    date: "30/12/2025",
    acta: "",
    valueLabor: 0,
    valueAdditionalDay: 0,
    valueFailedVisit: 0,
    valueCivilWorks: 0,
    valueTransport: 0,
    advanceAmount: 145000,
    totalAdvances: 0,
    iva: 0,
    reteFuente: 0,
    reteIca: 0,
    otherDiscounts: 0,
    subtotalService: 0,
    totalService: 0,
    balanceLabor: 0,
    balanceToPay: 0,
    status: 'Cerrado',
    observation: "Liquidado OK."
  },
    {
    id: "4641",
    caseId: "888961",
    orderDescription: "CASO 888961 - INSTALACION - UNE - REDITOS EMPRESARIALES - LEO - SAN ROQUE ANTIOQUIA - BARRIO MACEO",
    serviceType: "LEGALIZACION",
    department: "ANTIOQUIA",
    municipality: "MACEO",
    difficulty: "MEDIO",
    beneficiary: "FERNANDO CAICEDO",
    date: "30/12/2025",
    acta: "",
    valueLabor: 0,
    valueAdditionalDay: 0,
    valueFailedVisit: 0,
    valueCivilWorks: 0,
    valueTransport: 0,
    advanceAmount: 297000,
    totalAdvances: 0,
    iva: 0,
    reteFuente: 0,
    reteIca: 0,
    otherDiscounts: 0,
    subtotalService: 0,
    totalService: 0,
    balanceLabor: 0,
    balanceToPay: 0,
    status: 'Abierto',
    observation: ""
  }
];